### ISSUE TITLE
Fluentd crash when zookeeper returns no brokers or if zookeeper call fails

### ISSUE THREAD

**Issue by mohitkhanna** [htgc/fluent-plugin-kafka#11]
Hi @htgc ,

I am using v0.0.9 for this plugin. There are 2 specific exceptions we can see in our logs and both exceptions lead to **entire Fluentd Agent crashing**. Looks like these are uncaught errors in the code leading to full crash. Any input here would be helpful.

In both scenarios we were using the 'zookeeper' configuration and not the 'brokers'.

**Error 1:**
In this case Zookeeper is UP but no brokers are registered as they were down for maintenance.

```javascript
2015-03-20 09:08:12 +0000 [error]: unexpected error error="undefined method `each' for nil:NilClass"
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-kafka-0.0.9/lib/fluent/plugin/out_kafka_buffered.rb:39:in `configure'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/plugin/out_copy.rb:43:in `block in configure'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/plugin/out_copy.rb:32:in `each'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/plugin/out_copy.rb:32:in `configure'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/agent.rb:127:in `add_match'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/agent.rb:60:in `block in configure'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/agent.rb:54:in `each'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/agent.rb:54:in `configure'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/root_agent.rb:82:in `configure'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/engine.rb:97:in `configure'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/engine.rb:77:in `run_configure'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:399:in `run_configure'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:138:in `block in start'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:266:in `call'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:266:in `main_process'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:241:in `block in supervise'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:240:in `fork'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:240:in `supervise'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:134:in `start'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/command/fluentd.rb:167:in `<top (required)>'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/bin/fluentd:6:in `<top (required)>'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/bin/fluentd:23:in `load'
  2015-03-20 09:08:12 +0000 [error]: /usr/lib64/fluent/ruby/bin/fluentd:23:in `<top (required)>'
  2015-03-20 09:08:12 +0000 [error]: /usr/sbin/td-agent:7:in `load'
  2015-03-20 09:08:12 +0000 [error]: /usr/sbin/td-agent:7:in `<main>'
2015-03-20 09:08:12 +0000 [info]: process finished code=256
2015-03-20 09:08:12 +0000 [warn]: process died within 1 second. exit.
2015-03-20 09:10:29 +0000 [info]: reading config file path="/home/ec2-user/cloudmi/streaming/accounting/ph3-etl/td-agent.conf"
```

**Error 2:**

In this case Zookeeper itself was down for maintenance.

```javascript
2015-03-20 07:54:50 +0000 [error]: unexpected error error="response for meth: :get_children, args: [0, \"/brokers/ids\", nil, nil], not received within 30 seconds"
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/zookeeper-1.4.10/lib/zookeeper/continuation.rb:117:in `block in value'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/zookeeper-1.4.10/lib/zookeeper/continuation.rb:107:in `value'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/zookeeper-1.4.10/ext/c_zookeeper.rb:231:in `submit_and_block'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/zookeeper-1.4.10/ext/c_zookeeper.rb:40:in `get_children'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/zookeeper-1.4.10/lib/zookeeper/client_methods.rb:69:in `get_children'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-kafka-0.0.9/lib/fluent/plugin/out_kafka_buffered.rb:39:in `configure'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/plugin/out_copy.rb:43:in `block in configure'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/plugin/out_copy.rb:32:in `each'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/plugin/out_copy.rb:32:in `configure'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/agent.rb:127:in `add_match'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/agent.rb:60:in `block in configure'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/agent.rb:54:in `each'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/agent.rb:54:in `configure'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/root_agent.rb:82:in `configure'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/engine.rb:97:in `configure'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/engine.rb:77:in `run_configure'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:399:in `run_configure'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:138:in `block in start'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:266:in `call'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:266:in `main_process'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:241:in `block in supervise'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:240:in `fork'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:240:in `supervise'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/supervisor.rb:134:in `start'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/lib/fluent/command/fluentd.rb:167:in `<top (required)>'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.12.5/bin/fluentd:6:in `<top (required)>'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/bin/fluentd:23:in `load'
  2015-03-20 07:54:50 +0000 [error]: /usr/lib64/fluent/ruby/bin/fluentd:23:in `<top (required)>'
  2015-03-20 07:54:50 +0000 [error]: /usr/sbin/td-agent:7:in `load'
  2015-03-20 07:54:50 +0000 [error]: /usr/sbin/td-agent:7:in `<main>'
2015-03-20 07:54:50 +0000 [info]: process finished code=256
2015-03-20 07:54:50 +0000 [error]: fluentd main process died unexpectedly. restarting.
2015-03-20 07:54:50 +0000 [info]: starting fluentd-0.12.5
```

**Expected Behaviour:**

Temporary network glitches can occur or brokers could get migrated from one zookeeper to another leading to intermittent downtimes. This should lead to complete Fluentd agent crash. In such scenarios can the retry configuration be used? Or retry forever until issue resolved?

**Comment by htgc** [comment]
Thank you for using and sorry for inconvenience.
This plugin accesses Zookeeper only fluentd configures, so I will fix brokers are (re)configured in following case;

- Starts fluentd
- Failed transmitting messages

**Comment by mohitkhanna** [comment]
Thanks a lot @htgc . I will pull in the changes and see whether the fix works.
